idf_component_register(
    SRCS
        app_main.c
        hal_display_hw.c
        hal_input_hw.c
        hal_audio_hw.c
        ../../core/vm_host/vm_host.c
        ../../core/bindings/gfx_binding.c
        ../../core/bindings/event_binding.c
        ../../core/bindings/chrome_binding.c
        ../../core/bindings/audio_binding.c
        ../../core/gfx/gfx.c
        ../../core/audio/synth.c
        ../../core/kernel/kernel_window.c
        ../../core/kernel/kernel_spawn.c
        ../../core/kernel/kernel_router.c
        ../../core/kernel/kernel_audio.c
    INCLUDE_DIRS
        ../../core/vm_host
        ../../core/hal
        ../../core/gfx
        ../../core/audio
        ../../core/bindings
        ../../core/kernel
        freertos_compat
    REQUIRES mruby_component
)
